-- DGSL Site Register LIVE data setup
-- Run this in the LIVE Supabase SQL Editor before using the transferred
-- Bug Reports / website notification features. This only creates/adds the
-- feature tables and does not modify or delete existing handovers.

-- ------------------------------------------------------------
-- BUG REPORTS
-- ------------------------------------------------------------
create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  name text not null,
  trying_to_do text not null,
  report text not null,
  website_version text,
  page_url text,
  account_id uuid,
  status text not null default 'New',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.bug_reports add column if not exists name text;
alter table public.bug_reports add column if not exists trying_to_do text;
alter table public.bug_reports add column if not exists report text;
alter table public.bug_reports add column if not exists website_version text;
alter table public.bug_reports add column if not exists page_url text;
alter table public.bug_reports add column if not exists account_id uuid;
alter table public.bug_reports add column if not exists status text default 'New';
alter table public.bug_reports add column if not exists is_read boolean default false;
alter table public.bug_reports add column if not exists created_at timestamptz default now();

update public.bug_reports set status = 'New' where status is null;
update public.bug_reports set is_read = false where is_read is null;

alter table public.bug_reports enable row level security;

drop policy if exists "Allow authenticated live bug report read access" on public.bug_reports;
create policy "Allow authenticated live bug report read access"
on public.bug_reports
for select
to authenticated
using (true);

drop policy if exists "Allow authenticated live bug report insert access" on public.bug_reports;
create policy "Allow authenticated live bug report insert access"
on public.bug_reports
for insert
to authenticated
with check (true);

drop policy if exists "Allow authenticated live bug report update access" on public.bug_reports;
create policy "Allow authenticated live bug report update access"
on public.bug_reports
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Allow authenticated live bug report delete access" on public.bug_reports;
create policy "Allow authenticated live bug report delete access"
on public.bug_reports
for delete
to authenticated
using (true);

-- ------------------------------------------------------------
-- WEBSITE VERSION NOTIFICATIONS
-- ------------------------------------------------------------
create table if not exists public.site_notifications (
  id bigint generated by default as identity primary key,
  version text not null unique,
  title text not null default 'Website updated',
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.site_notifications enable row level security;

drop policy if exists "Allow authenticated live notification read access" on public.site_notifications;
create policy "Allow authenticated live notification read access"
on public.site_notifications
for select
to authenticated
using (true);

-- GitHub Actions uses the Supabase service-role key for notification writes.
-- Service-role access bypasses RLS, so no INSERT policy is required.
